name: Validate Workflow Syntax

on:
  pull_request:
    paths:
      - '.github/workflows/**'

permissions:
  pull-requests: write   # Enable inline PR annotations

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: devops-actions/actionlint@v0.1.12
